# Generated by Django 4.2.11 on 2024-09-05 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('profile_pic', models.ImageField(default='/profilepics/default.png', upload_to='profilepics')),
                ('bio', models.CharField(default='working on something big', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('length', models.IntegerField(default=0)),
                ('description', models.CharField(default='my new episode', max_length=500)),
                ('link', models.URLField()),
                ('audiofile', models.FileField(upload_to='episodes')),
                ('all_blocs', models.BooleanField(default=True)),
                ('night_bloc', models.BooleanField(default=False)),
                ('morning_bloc', models.BooleanField(default=False)),
                ('afternoon_bloc', models.BooleanField(default=False)),
                ('evening_bloc', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.CharField(default='#222222', max_length=10)),
                ('primary', models.CharField(default='#c2681e', max_length=10)),
                ('accent', models.CharField(default='#111111', max_length=10)),
                ('text', models.CharField(default='#ffffff', max_length=10)),
                ('secondary_text', models.CharField(default='#cccccc', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.episode')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(default='my new show', max_length=500)),
                ('one_shot', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('banner', models.ImageField(default='/showbanners/defaultbanner.png', upload_to='showbanners')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.dj')),
                ('show_theme', models.ForeignKey(default=website.models.get_default_theme, on_delete=django.db.models.deletion.CASCADE, to='website.theme')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slots', models.ManyToManyField(to='website.slot')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.show'),
        ),
        migrations.AddField(
            model_name='dj',
            name='profile_theme',
            field=models.ForeignKey(default=website.models.get_default_theme, on_delete=django.db.models.deletion.CASCADE, to='website.theme'),
        ),
        migrations.AddField(
            model_name='dj',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
