# Generated by Django 4.2.11 on 2024-09-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_dj_profile_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='show',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
