# Generated by Django 4.2.11 on 2024-09-06 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_dj_bio_alter_episode_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='episode',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
